import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@/generated/prisma';

const prisma = new PrismaClient();

// GET /api/news - 获取新闻列表（前台）
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const category = searchParams.get('category');
    const featured = searchParams.get('featured');
    const source = searchParams.get('source'); // manual, instagram, wechat, auto
    const limit = searchParams.get('limit');
    const page = searchParams.get('page') || '1';
    const pageSize = parseInt(searchParams.get('pageSize') || '12');
    
    const skip = (parseInt(page) - 1) * pageSize;
    
    // 构建查询条件
    const where: any = {
      // 只返回已发布的新闻
      publishedAt: {
        lte: new Date()
      }
    };
    
    if (category && category !== 'all') {
      where.category = category;
    }
    
    if (featured === 'true') {
      where.featured = true;
    }
    
    if (source && source !== 'all') {
      where.source = source;
    }
    
    // 获取新闻列表
    const news = await prisma.news.findMany({
      where,
      orderBy: {
        publishedAt: 'desc'
      },
      skip: limit ? 0 : skip,
      take: limit ? parseInt(limit) : pageSize,
      select: {
        id: true,
        slug: true,
        title: true,
        excerpt: true,
        category: true,
        authorName: true,
        authorTitle: true,
        authorAvatar: true,
        publishedAt: true,
        readTime: true,
        image: true,
        tags: true,
        featured: true,
        views: true,
        likes: true,
        source: true,
        sourceUrl: true,
        autoGenerated: true
      }
    });
    
    // 如果不是限制数量的请求，还需要返回总数
    let total = 0;
    if (!limit) {
      total = await prisma.news.count({ where });
    }
    
    return NextResponse.json({
      success: true,
      data: {
        items: news,
        total,
        page: parseInt(page),
        pageSize,
        totalPages: Math.ceil(total / pageSize)
      }
    });
    
  } catch (error) {
    console.error('获取新闻列表失败:', error);
    return NextResponse.json(
      { success: false, message: '获取新闻列表失败' },
      { status: 500 }
    );
  }
}